//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Таблица_видов_топлива
    {
        public Nullable<int> id_post { get; set; }
        public int id_vid { get; set; }
        public Nullable<int> price { get; set; }
        public string Name { get; set; }
    }
}
