//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Таблица_учета_остатков
    {
        public int id_accounting { get; set; }
        public Nullable<int> id_vid { get; set; }
        public Nullable<int> data { get; set; }
        public Nullable<int> volume_day { get; set; }
        public Nullable<int> volume_price { get; set; }
    }
}
